cache:
  directories:
    - $HOME/.composer/cache/files

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ $DEPS == 'lowest' ]]; then composer update --prefer-stable --no-interaction --prefer-lowest ; fi
  - if [[ $DEPS == 'latest' ]]; then composer update --prefer-stable --no-interaction ; fi

script:
  - ./vendor/bin/phpunit
