language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ $DEPS == 'lowest' ]]; then composer update --prefer-stable --no-interaction --prefer-lowest ; fi
  - if [[ $DEPS == 'latest' ]]; then composer update --prefer-stable --no-interaction ; fi

script:
  - ./vendor/bin/phpunit
